services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: alex@pg.admin
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "15432:80"
  postgres:
    image: postgres:16.3
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=reptopetrol
      - POSTGRES_PASSWORD=reptopetrol
      - POSTGRES_DB=reptopetrol
    volumes:
      - ./data:/var/lib/postgresql/data
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    container_name: mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongouser:mongopassword@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password