application:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration:
      access: 86400000
      refresh: 604800000

spring:
  application:
    name: reptopetrol-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/reptopetrol
    username: reptopetrol
    password: reptopetrol
  docker:
    compose:
      enabled: true
      file: docker_compose.yaml
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  mongodb:
    # TODO change database name
    uri: mongodb://mongouser:mongopassword@localhost:27017/teleleu?authSource=admin
    representation:
      uuid: standard
  mvc:
    hiddenmethod:
      filter:
        enabled: true # enabled so that I can set the hidden method to DELETE for the delete buttons in the index pages
