spring:
  application:
    name: reptopetrol-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/reptopetrol
    username: reptopetrol
    password: reptopetrol
  docker:
    compose:
      enabled: true
      file: docker_compose.yaml
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  mongodb:
    uri: mongodb://mongouser:mongopassword@localhost:27017/teleleu?authSource=admin
